version: '3.8'
services:

  redis:
    image: redis:6-alpine

  web:
    build: .
    image: web
    container_name: web
    ports:
      - 5001:5001
    command: python -m flask run --port 5001 --host=0.0.0.0
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.server.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A src.llm_gen.celery worker --loglevel=info
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.server.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis